### ISSUE TITLE
Hack only updated packages?

### ISSUE THREAD

**Issue by bebraw** [cdaringe/lerna-npm-readme-hack#2]
Hi,

I have set this up at [reactabular](https://github.com/reactabular/reactabular). There's a publish script like `"publish": "lerna publish && lerna-npm-readme-hack",`. The problem is that it runs the hack against all packages, not just the changed ones.

Would it be possible to alter it somehow (cache old versions for a lookup?) to hack only the updated ones? Now it's doing quite a bit of extra work as it goes through all of them.

**Comment by cdaringe** [comment]
hey @bebraw, reactublar is great!  openly, i'm likely not keen on putting _much more work_ into this package, simply because of availability, and my perceived level of effort to achieve your request.  i guess it boils down to the notion that i don't want to get into the lerna internals.  who knows, maybe we wouldn't have to.  if you'd like to take a stab, id say go for it. you can be a git/npm owner of the package too, if desired.

something i am willing to work on though, if you think it would also meet your needs, is just speed all of this way up, and do all of the hacks in parallel, vs my current sync strategy?

**Comment by bebraw** [comment]
@cdaringe Yeah, hacking on Lerna internals would be a scary prospect. 👍 

How about this?

1. Instead of `lerna publish && lerna-npm-readme-hack` we do `lerna-npm-readme-hack && lerna publish && lerna-npm-readme-hack`
2. The first pass figures out the currently available published versions and writes them somewhere (`.hack` or so)
3. The second pass detects the file, performs the check again, and does a diff.
4. Based on diff we do what it does right now.

I think steps 2/3 would be something along this:

```javascript
const cache = glob.sync('*/**/package.json').
  map(f => require(f)).
  map(({name, version}) => ({ name, version}));

// Write now
```

That said, I would be happy with a little speedup if maintaining a version cache feels too hacky.

**Comment by cdaringe** [comment]
`lerna updated` may offer what is desired for step 1.  it could feasibly feasibly parse and pipe that to a `.hack`, which is a hilarious and perfectly named extension by the way.  then step 3 could be modified to look like `lerna-npm-readme-hack --from-hackfile [path]`

**Comment by bebraw** [comment]
Yeah, that would work.
